# Generated by Django 5.0.6 on 2024-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2024-12-31'),
            preserve_default=False,
        ),
    ]
